<div class="alert alert-block alert-info">
    
# Summer Research Project
## Dataset Modification and Preprocessing

    
Student Name: Vincent
    
Student ID: 30052386
    
Environment: Python 3 (Jupyter Notebook)

Libraries used:
* pandas
    
Files used that are provided by Monash University:
* 2021_Clayton Solar PV.xlsx
* 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv
* -37.912_145.134_Solcast_PT5M.csv
    
</div>

<div class="alert alert-block alert-danger">
    
## Table of Contents

</div>    

[1. Introduction](#Intro) <br>
[2. Data Preprocessing](#data_prepro) <br>
$\;\;\;\;$[2.1. Preparing 2021_Clayton Solar PV.xlsx](#first_df) <br>
$\;\;\;\;$[2.2. Preparing 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv](#second_df) <br>
$\;\;\;\;\;\;\;\;$[2.2.1. Combining 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv and 2021_Clayton Solar PV.xlsx Files](#3_df) <br>
$\;\;\;\;$[2.3. Preparing Weather Dataset](#4_df) <br>
[3. Creating Time Series Data Analytics and Visualization App's Datasets](#TS1) <br>
$\;\;\;\;$[3.4. Distribution, Missing Value, Outlier, and Trend Pages Dataset](#TS2) <br>
$\;\;\;\;$[3.5. Feature Selection Page and Random Forest Modelling Dataset](#TS3) <br>
$\;\;\;\;\;\;\;\;$[3.5.1. Feature Engineering](#feature_engineering) <br>
[4. Summary](#summary) <br>

<div class="alert alert-block alert-info">
    
## 1. Introduction <a class="anchor" name="Intro"></a>
    
</div>

This report will demonstrate each step of data preprocessing for the datasets that are compatible in the Time Series Data Analytics and Visualization App, Feature Selection Page and Random Forest Modelling of the Photovoltaic (PV) Generation. There are three raw files that have been used to create the remaining datasets namely 2021_Clayton Solar PV.xlsx, 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv, and -37.912_145.134_Solcast_PT5M.csv. Following are explanations of the files:

- **2021_Clayton Solar PV.xlsx:** The Photovoltaic (PV) generation data of 32 Monash University Clayton buildings from 1/1/2021 12:00 AM to 31/12/2021 11:45 PM
- **2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv:** The Photovoltaic (PV) generation data of 30 Monash University Clayton buildings from 1/7/2020 12:15 AM to 1/7/2021 12:00 AM (i.e., this file does not contain LV_Briggs_85B.Solar_Main_Supply and LV_Jackomos_B85A.Solar_Main_Supply buildings)
- **-37.912_145.134_Solcast_PT5M.csv:** The weather data in the given location (In this case, Latitude: -37.912 and Longitude: 145.134) from 31/12/2015 12:15 AM to 16/7/2021 10:55 PM

**Important:** Before running the codes below, it is required to have a folder called data in the "./data" working directory with all three files mentioned above.

<div class="alert alert-block alert-info">

## 2. Data Preprocessing <a class="anchor" name="data_prepro"></a>

</div>

<div class="alert alert-block alert-warning">

### 2.1. Preparing 2021_Clayton Solar PV.xlsx (Timestamp: From 1/1/2021 12:00 AM to 31/12/2021 11:45 PM) <a class="anchor" name="first_df"></a>

 </div>

In this section, the used file is **2021_Clayton Solar PV.xlsx**. The steps to prepare it are as follow:

1. Import pandas library;
2. Read 2021_Clayton Solar PV.xlsx file (i.e., only sheet 1);
3. Remove the first two rows because it does not contain any important information about the PV generation process;
4. Rename the column "0" to "ReadTime";
5. Reset Index because we remove the first two columns in the third step;
6. Drop "Unnamed: 33" column;
7. Reformat ReadTime variable into DD/MM/YYYY HH:MM AM/PM date format (without 0 in the front of day or month such as 01, 02, etc.);
8. Write the final dataset into PV_data_first.csv file and include the observation number.

In [1]:
# Import Library
import pandas as pd

In [2]:
# Read .xlsx file
xls = pd.ExcelFile('./data/2021_Clayton Solar PV.xlsx')
PV_df = pd.read_excel(xls, 'Sheet1')

In [3]:
# Print the reading result
PV_df

,0,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,LV_Biomedical_Sciences_76.Solar_Main_Supply,LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified,LV_Briggs_85B.Solar_Main_Supply,LV_Buildings_and_Property_56.Solar_Main_Supply,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Chancellery_96.Solar_Main_Supply,LV_East_41.Solar_Main_Supply,...,LV_Physics_27.Solar_Main_Supply,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_TED_B94.DB_Roof_Solar,LV_Turner_Hall_87.Solar_Main_Supply_unverified,Unnamed: 33,Total Clayton solar connected to main HV NMI
0,Timestamp [AEST]\n**No daylight savings adjust...,Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),...,Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),Real Energy Into the Load (kWh),NaN,kWh
1,NaN,All Times,All Times,All Times,All Times,All Times,All Times,All Times,All Times,All Times,...,All Times,All Times,All Times,All Times,All Times,All Times,All Times,All Times,NaN,All Times
2,1/01/2021 12:00 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0,0,0,0.007,NaN,0.006,NaN,0,NaN,0.036
3,1/01/2021 12:15 AM,0.002,0,0,0,0,0.012,0,0.002,0,...,0,0,0,0.008,NaN,0.006,NaN,0,NaN,0.036
4,1/01/2021 12:30 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0,0,0,0.008,NaN,0.006,NaN,0,NaN,0.037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35033,31/12/2021 10:45 PM,NaN,NaN,0,NaN,NaN,0.013,0,0.003,0,...,NaN,0,0,0.007,0,0.006,0,0,NaN,0.033
35034,31/12/2021 11:00 PM,NaN,0,0,0,0.001,0.013,NaN,NaN,0,...,0,0,NaN,0.008,0,0.006,0.001,NaN,NaN,0.037
35035,31/12/2021 11:15 PM,0.008,NaN,NaN,0,NaN,0.013,0,0.004,NaN,...,0,0,0,0.007,0,0.005,0.001,0,NaN,0.043
35036,31/12/2021 11:30 PM,0.002,0,0,0,0,0.014,0,0.002,0,...,0,0,0,NaN,NaN,0.006,0.001,0,NaN,0.031
35037,31/12/2021 11:45 PM,NaN,NaN,NaN,0,NaN,0.013,NaN,NaN,0,...,NaN,0,NaN,0.015,0,0.006,0.001,0,NaN,0.041

In [4]:
# Remove the first two rows
PV_df_final = PV_df.iloc[3:]

# Rename 0 column into ReadTime column by using indexing method
PV_df_final.columns.values[0] = "ReadTime"

# Reset Index
PV_df_final.reset_index(drop=True, inplace=True)

# Drop "Unnamed: 33" column
PV_df_final = PV_df_final.loc[:, ~PV_df_final.columns.isin(['Unnamed: 33'])]

PV_df_final

,ReadTime,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,LV_Biomedical_Sciences_76.Solar_Main_Supply,LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified,LV_Briggs_85B.Solar_Main_Supply,LV_Buildings_and_Property_56.Solar_Main_Supply,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Chancellery_96.Solar_Main_Supply,LV_East_41.Solar_Main_Supply,...,LV_North_Pavilion.MSB_PV_DB,LV_Physics_27.Solar_Main_Supply,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_TED_B94.DB_Roof_Solar,LV_Turner_Hall_87.Solar_Main_Supply_unverified,Total Clayton solar connected to main HV NMI
0,1/01/2021 12:15 AM,0.002,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
1,1/01/2021 12:30 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.037
2,1/01/2021 12:45 AM,0.003,0,0,0,0,0.011,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
3,1/01/2021 1:00 AM,0.002,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
4,1/01/2021 1:15 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35030,31/12/2021 10:45 PM,NaN,NaN,0,NaN,NaN,0.013,0,0.003,0,...,0.001,NaN,0,0,0.007,0,0.006,0,0,0.033
35031,31/12/2021 11:00 PM,NaN,0,0,0,0.001,0.013,NaN,NaN,0,...,0.001,0,0,NaN,0.008,0,0.006,0.001,NaN,0.037
35032,31/12/2021 11:15 PM,0.008,NaN,NaN,0,NaN,0.013,0,0.004,NaN,...,0.001,0,0,0,0.007,0,0.005,0.001,0,0.043
35033,31/12/2021 11:30 PM,0.002,0,0,0,0,0.014,0,0.002,0,...,0.001,0,0,0,NaN,NaN,0.006,0.001,0,0.031
35034,31/12/2021 11:45 PM,NaN,NaN,NaN,0,NaN,0.013,NaN,NaN,0,...,0.001,NaN,0,NaN,0.015,0,0.006,0.001,0,0.041

In [5]:
# Reformat ReadTime

# Step 1. Split the date and time into 2 separate variables
PV_df_final[['datePV','timePV']] = PV_df_final["ReadTime"].str.split(" ", 1, expand=True)

# Step 2. Re-format the datePV variable
# Split the datePV variable
PV_df_final[['dayPV','monthPV', 'yearPV']] = PV_df_final['datePV'].str.split('/',expand=True)
# Change monthPV format by deleting front 0 (e.g. 01, 02, etc.)
PV_df_final['monthPV'] = PV_df_final['monthPV'].apply(lambda t: str(int(t)))
# Reassemble the date format of DD/MM/YYYY
PV_df_final["datePV"] = PV_df_final[["dayPV", "monthPV", "yearPV"]].apply("/".join, axis=1)

# Step 3. Re-format the ReadTime variable into DD/MM/YYYY HH:MM AM/PM date format (without 0 in the front of day or month such as 01, 02, etc.)
PV_df_final["ReadTime"] = PV_df_final[["datePV", "timePV"]].apply(" ".join, axis=1)

# Drop the previously created helper variables
PV_df_final = PV_df_final.drop(['datePV', 'timePV', 'yearPV', 'monthPV', 'dayPV'], axis=1)

PV_df_final

,ReadTime,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,LV_Biomedical_Sciences_76.Solar_Main_Supply,LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified,LV_Briggs_85B.Solar_Main_Supply,LV_Buildings_and_Property_56.Solar_Main_Supply,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Chancellery_96.Solar_Main_Supply,LV_East_41.Solar_Main_Supply,...,LV_North_Pavilion.MSB_PV_DB,LV_Physics_27.Solar_Main_Supply,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_TED_B94.DB_Roof_Solar,LV_Turner_Hall_87.Solar_Main_Supply_unverified,Total Clayton solar connected to main HV NMI
0,1/1/2021 12:15 AM,0.002,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
1,1/1/2021 12:30 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.037
2,1/1/2021 12:45 AM,0.003,0,0,0,0,0.011,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
3,1/1/2021 1:00 AM,0.002,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
4,1/1/2021 1:15 AM,0.003,0,0,0,0,0.012,0,0.002,0,...,0.001,0,0,0,0.008,NaN,0.006,NaN,0,0.036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35030,31/12/2021 10:45 PM,NaN,NaN,0,NaN,NaN,0.013,0,0.003,0,...,0.001,NaN,0,0,0.007,0,0.006,0,0,0.033
35031,31/12/2021 11:00 PM,NaN,0,0,0,0.001,0.013,NaN,NaN,0,...,0.001,0,0,NaN,0.008,0,0.006,0.001,NaN,0.037
35032,31/12/2021 11:15 PM,0.008,NaN,NaN,0,NaN,0.013,0,0.004,NaN,...,0.001,0,0,0,0.007,0,0.005,0.001,0,0.043
35033,31/12/2021 11:30 PM,0.002,0,0,0,0,0.014,0,0.002,0,...,0.001,0,0,0,NaN,NaN,0.006,0.001,0,0.031
35034,31/12/2021 11:45 PM,NaN,NaN,NaN,0,NaN,0.013,NaN,NaN,0,...,0.001,NaN,0,NaN,0.015,0,0.006,0.001,0,0.041

In [6]:
# Generate csv files
PV_df_final.to_csv('./data/PV_data_first.csv', index = False)

<div class="alert alert-block alert-warning">

### 2.2. Preparing 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv (Timestamp: From 1/7/2020 12:15 AM to 1/7/2021 12:00 AM) <a class="anchor" name="second_df"></a>

 </div>

In this section, the used file is **2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv**. The steps to prepare it are as follow:

1. Import pandas library;
2. Read 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv;
3. Create Total Clayton solar connected to main HV NMI variable by summing all the buildings' PVs;
4. Reformat the ReadTime from YYYY-MM-DD HH:MM:SS into DD/MM/YYYY HH:MM AM/PM date format.

In [7]:
# Import Library
import pandas as pd

In [8]:
# Read CSV
PV_data = pd.read_csv("./data/2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv")

In [9]:
# Print the reading result
PV_data

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,LV_N1_Building_Carpark.West_Park_Solar_Feed,LV_Green_Chemical_Futures_86.Main_Solar_Supply-unverified,LV_Turner_Hall_87.Solar_Main_Supply_unverified,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply
0,2020-07-01 00:15:00,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001
1,2020-07-01 00:30:00,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000
2,2020-07-01 00:45:00,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000
3,2020-07-01 01:00:00,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000
4,2020-07-01 01:15:00,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2021-06-30 23:00:00,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002
35036,2021-06-30 23:15:00,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002
35037,2021-06-30 23:30:00,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002
35038,2021-06-30 23:45:00,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002
35039,2021-07-01 00:00:00,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [10]:
# Create Total Clayton solar connected to main HV NMI variable
PV_data['Total Clayton solar connected to main HV NMI']=PV_data.iloc[:,2:len(PV_data.axes[1])].sum(axis=1)

# Re-format the ReadTime so that the 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv and PV_data_first.csv files have 
# a similar date format
# Step 1. Split the date and time into 2 separate variables
PV_data[['datePV','timePV']] = PV_data["ReadTime"].str.split(" ", 1, expand=True)

# Step 2. Re-format the datePV variable
# Split the datePV variable
PV_data[['yearPV','monthPV', 'dayPV']] = PV_data['datePV'].str.split('-',expand=True)
# Change dayPV format by deleting front 0 (e.g. 01, 02, etc.)
PV_data['dayPV'] = PV_data['dayPV'].apply(lambda t: str(int(t)))
# Change monthPV format by deleting front 0 (e.g. 01, 02, etc.)
PV_data['monthPV'] = PV_data['monthPV'].apply(lambda t: str(int(t)))
# Change the format from YYYY-MM-DD into DD/MM/YYYY
PV_data["datePV"] = PV_data[["dayPV", "monthPV", "yearPV"]].apply("/".join, axis=1)

# Step 3. Re-format the timePV variable
# Split the timePV variable
PV_data[['hourPV','minutePV', 'secondPV']] = PV_data['timePV'].str.split(':',expand=True)
# Create PM or AM
PV_data['AMorPM'] = PV_data['hourPV'].apply(lambda t: "AM" if int(t) / 12 < 1 else "PM")
# Change the format from HH:MM:SS into HH:MM AM/PM
PV_data['hourPV'] = PV_data['hourPV'].apply(lambda t: "12" if t == "00" else t)
PV_data['hourPV'] = PV_data['hourPV'].apply(lambda t: str(int(t) - 12) if int(t) > 12 else t)
# Change hourPV format by deleting front 0 (e.g. 01, 02, etc.)
PV_data['hourPV'] = PV_data['hourPV'].apply(lambda t: str(int(t)))
PV_data["timePV"] = PV_data[["hourPV", "minutePV"]].apply(":".join, axis=1)
PV_data["timePV"] = PV_data[["timePV", "AMorPM"]].apply(" ".join, axis=1)

# Step 4. Re-format the ReadTime
PV_data["ReadTime"] = PV_data[["datePV", "timePV"]].apply(" ".join, axis=1)

# Step 5. Exclude previously created helper variables
PV_data = PV_data.drop(['datePV', 'timePV', 'yearPV', 'monthPV', 'dayPV', 'hourPV', 'minutePV', 'secondPV', 'AMorPM'], axis=1)

In [11]:
PV_data

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,LV_Green_Chemical_Futures_86.Main_Solar_Supply-unverified,LV_Turner_Hall_87.Solar_Main_Supply_unverified,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply,Total Clayton solar connected to main HV NMI
0,1/7/2020 12:15 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001,0.025
1,1/7/2020 12:30 AM,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.025
2,1/7/2020 12:45 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.024
3,1/7/2020 1:00 AM,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.026
4,1/7/2020 1:15 AM,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,30/6/2021 11:00 PM,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.020
35036,30/6/2021 11:15 PM,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.022
35037,30/6/2021 11:30 PM,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.023
35038,30/6/2021 11:45 PM,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.020
35039,1/7/2021 12:00 AM,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.019

<div class="alert alert-block alert-warning">

#### 2.2.1. Combining 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv and 2021_Clayton Solar PV.xlsx Files (Timestamp after Combining: From 1/7/2020 12:15 AM to 31/12/2021 11:45 PM) <a class="anchor" name="3_df"></a>

 </div>

In this section, the used files are **PV_data_first.csv** (generated from section 2.1) and **2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv** (generated from section 2.2). The steps to combine them are as follow:

1. Read PV_data_first.csv (generated from section 2.1);
2. Remove the duplicate data from both datasets;
3. Write the final dataset into PV_data.csv file and include the observation number.

In [12]:
# Read CSV
PV_first = pd.read_csv("./data/PV_data_first.csv") # from 2021_Clayton Solar PV.xlsx file

In [13]:
# Step 1. Listing all the data (in ReadTime) in the 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv
list_1 = PV_data['ReadTime'].tolist()

# Step 2. Filter all the rows that are not a duplicate data in the 2021_Clayton Solar PV.xlsx or PV_data_first.csv
PV_data2 = PV_first.loc[~PV_first['ReadTime'].isin(list_1)]

In [14]:
PV_data2

,ReadTime,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,LV_Biomedical_Sciences_76.Solar_Main_Supply,LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified,LV_Briggs_85B.Solar_Main_Supply,LV_Buildings_and_Property_56.Solar_Main_Supply,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Chancellery_96.Solar_Main_Supply,LV_East_41.Solar_Main_Supply,...,LV_North_Pavilion.MSB_PV_DB,LV_Physics_27.Solar_Main_Supply,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_TED_B94.DB_Roof_Solar,LV_Turner_Hall_87.Solar_Main_Supply_unverified,Total Clayton solar connected to main HV NMI
17376,1/7/2021 12:15 AM,0.003,0.0,0.0,0.0,0.000,0.012,0.0,0.002,0.0,...,0.001,0.0,0.0,0.0,0.007,0.0,NaN,NaN,0.0,0.029
17377,1/7/2021 12:30 AM,0.002,0.0,0.0,0.0,0.001,0.013,0.0,0.002,0.0,...,0.000,0.0,0.0,0.0,0.008,0.0,NaN,NaN,0.0,0.031
17378,1/7/2021 12:45 AM,0.003,0.0,0.0,0.0,0.002,0.012,0.0,0.001,0.0,...,0.000,0.0,0.0,0.0,0.007,0.0,NaN,NaN,0.0,0.030
17379,1/7/2021 1:00 AM,0.002,0.0,0.0,0.0,0.001,0.012,0.0,0.002,0.0,...,0.000,0.0,0.0,0.0,0.008,0.0,NaN,NaN,0.0,0.029
17380,1/7/2021 1:15 AM,0.003,0.0,0.0,0.0,0.001,0.012,0.0,0.002,0.0,...,0.000,0.0,0.0,0.0,0.007,0.0,NaN,NaN,0.0,0.030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35030,31/12/2021 10:45 PM,NaN,NaN,0.0,NaN,NaN,0.013,0.0,0.003,0.0,...,0.001,NaN,0.0,0.0,0.007,0.0,0.006,0.000,0.0,0.033
35031,31/12/2021 11:00 PM,NaN,0.0,0.0,0.0,0.001,0.013,NaN,NaN,0.0,...,0.001,0.0,0.0,NaN,0.008,0.0,0.006,0.001,NaN,0.037
35032,31/12/2021 11:15 PM,0.008,NaN,NaN,0.0,NaN,0.013,0.0,0.004,NaN,...,0.001,0.0,0.0,0.0,0.007,0.0,0.005,0.001,0.0,0.043
35033,31/12/2021 11:30 PM,0.002,0.0,0.0,0.0,0.000,0.014,0.0,0.002,0.0,...,0.001,0.0,0.0,0.0,NaN,NaN,0.006,0.001,0.0,0.031
35034,31/12/2021 11:45 PM,NaN,NaN,NaN,0.0,NaN,0.013,NaN,NaN,0.0,...,0.001,NaN,0.0,NaN,0.015,0.0,0.006,0.001,0.0,0.041

In [15]:
# Step 4. Combine 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv and 2021_Clayton Solar PV.xlsx files
result = pd.concat([PV_data, PV_data2], ignore_index=True, sort=False)

result

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply,Total Clayton solar connected to main HV NMI,LV_Briggs_85B.Solar_Main_Supply,LV_Jackomos_B85A.Solar_Main_Supply
0,1/7/2020 12:15 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.001,0.025,NaN,NaN
1,1/7/2020 12:30 AM,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.025,NaN,NaN
2,1/7/2020 12:45 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
3,1/7/2020 1:00 AM,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.026,NaN,NaN
4,1/7/2020 1:15 AM,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52694,31/12/2021 10:45 PM,0.007,0.000,0.006,0.001,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.0,0.000,0.003,0.033,NaN,0.002
52695,31/12/2021 11:00 PM,0.008,0.000,0.006,0.001,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.037,0.001,NaN
52696,31/12/2021 11:15 PM,0.007,0.000,0.005,0.001,0.0,0.008,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,0.0,0.001,0.004,0.043,NaN,0.000
52697,31/12/2021 11:30 PM,NaN,NaN,0.006,0.001,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.001,0.002,0.031,0.000,0.001
52698,31/12/2021 11:45 PM,0.015,0.000,0.006,0.001,0.0,NaN,0.0,NaN,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.041,NaN,NaN

In [16]:
# Step 5. Generate csv files
result.to_csv('./data/PV_data.csv', index = False)

Below is the summary of which building's data that is not available in the 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv but available in the 2021_Clayton Solar PV.xlsx. **n** in the summary table will indicate those buildings.

In [17]:
""" [The Summary of All Buildings -> n shows the buildings that are not available in the 2020-07 to 2021-06 
    Clayton PV Data (verified) Pivoted.csv]
    
 0   observation.no                                             35035 non-null  int64   n
 1   TimestampPV                                                35035 non-null  object  x
 2   Campus_Centre_10.Solar_Main_Supply                         34808 non-null  float64 x
 3   LV_Accident_Research_Centre_70.Solar_Main_Supply           34825 non-null  float64 x
 4   LV_Biomedical_Sciences_76.Solar_Main_Supply                34317 non-null  float64 x
 5   LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified     34835 non-null  float64 x
 6   LV_Briggs_85B.Solar_Main_Supply                            33953 non-null  float64 n
 7   LV_Buildings_and_Property_56.Solar_Main_Supply             34811 non-null  float64 x
 8   LV_Campbell_Hall_89.Solar_Main_Supply-unverified           34826 non-null  float64 x
 9   LV_Chancellery_96.Solar_Main_Supply                        30650 non-null  float64 x
 10  LV_East_41.Solar_Main_Supply                               34698 non-null  float64 x
 11  LV_Engineering_37.East_Workshop_Solar_Main_Supply          35023 non-null  float64 x
 12  LV_Engineering_72.Solar_Main_Supply                        34774 non-null  float64 x
 13  LV_Facilities_Services_South_East_40.Solar_Main_Supply     34809 non-null  float64 x
 14  LV_Green_Chemical_Futures_86.Main_Solar_Supply-unverified  34984 non-null  float64 x
 15  LV_Hargrave-Andrew_Library_30.Solar_Main_Supply            34773 non-null  float64 x
 16  LV_Holman_Hall_88.Solar_Main_Supply-unverified             34814 non-null  float64 x
 17  LV_Information_Services_67.Solar_Main_Supply               34774 non-null  float64 x
 18  LV_Jackomos_B85A.Solar_Main_Supply                         22211 non-null  float64 n
 19  LV_Law_Theatres_12.Solar_Main_Supply                       34770 non-null  float64 x
 20  LV_Logan_Hall_90.Solar_Main_Supply                         34756 non-null  float64 x
 21  LV_LTB_1_92.MSB1_DB_PV1                                    34816 non-null  float64 x
 22  LV_LTB_2_92.MSB2_DB_PV2                                    34821 non-null  float64 x
 23  LV_Medical_13F.Solar_Main_Supply                           34794 non-null  float64 x
 24  LV_N1_Building_Carpark.West_Park_Solar_Feed                31469 non-null  float64 x
 25  LV_North_Pavilion.MSB_PV_DB                                34389 non-null  float64 x
 26  LV_Physics_27.Solar_Main_Supply                            34774 non-null  float64 x
 27  LV_Robert_Blackwood_Hall_2.Main_Solar_Supply               34991 non-null  float64 x
 28  LV_Science_Theatres_East_25.Solar_Main_Supply              34738 non-null  float64 x
 29  LV_Sport_01.PVDB-DB-A                                      33460 non-null  float64 x
 30  LV_Sport_01.PVDB-DB-B                                      18961 non-null  float64 x
 31  LV_Sport_01.PVDB-MSSB                                      30112 non-null  float64 x
 32  LV_TED_B94.DB_Roof_Solar                                   13692 non-null  float64 x
 33  LV_Turner_Hall_87.Solar_Main_Supply_unverified             34808 non-null  float64 x
 34  Total Clayton solar connected to main HV NMI               35035 non-null  float64 n
 """

' [The Summary of All Buildings -> n shows the buildings that are not available in the 2020-07 to 2021-06 \n    Clayton PV Data (verified) Pivoted.csv]\n    \n 0   observation.no                                             35035 non-null  int64   n\n 1   TimestampPV                                                35035 non-null  object  x\n 2   Campus_Centre_10.Solar_Main_Supply                         34808 non-null  float64 x\n 3   LV_Accident_Research_Centre_70.Solar_Main_Supply           34825 non-null  float64 x\n 4   LV_Biomedical_Sciences_76.Solar_Main_Supply                34317 non-null  float64 x\n 5   LV_Biomedical_Sciences_77.Solar_Main_Supply-unverified     34835 non-null  float64 x\n 6   LV_Briggs_85B.Solar_Main_Supply                            33953 non-null  float64 n\n 7   LV_Buildings_and_Property_56.Solar_Main_Supply             34811 non-null  float64 x\n 8   LV_Campbell_Hall_89.Solar_Main_Supply-unverified           34826 non-null  float64 x\n 9   LV_Chancellery_96.Solar_Main_Supply                        30650 non-null  float64 x\n 10  LV_East_41.Solar_Main_Supply                               34698 non-null  float64 x\n 11  LV_Engineering_37.East_Workshop_Solar_Main_Supply          35023 non-null  float64 x\n 12  LV_Engineering_72.Solar_Main_Supply                        34774 non-null  float64 x\n 13  LV_Facilities_Services_South_East_40.Solar_Main_Supply     34809 non-null  float64 x\n 14  LV_Green_Chemical_Futures_86.Main_Solar_Supply-unverified  34984 non-null  float64 x\n 15  LV_Hargrave-Andrew_Library_30.Solar_Main_Supply            34773 non-null  float64 x\n 16  LV_Holman_Hall_88.Solar_Main_Supply-unverified             34814 non-null  float64 x\n 17  LV_Information_Services_67.Solar_Main_Supply               34774 non-null  float64 x\n 18  LV_Jackomos_B85A.Solar_Main_Supply                         22211 non-null  float64 n\n 19  LV_Law_Theatres_12.Solar_Main_Supply                       34770 non-null  float64 x\n 20  LV_Logan_Hall_90.Solar_Main_Supply                         34756 non-null  float64 x\n 21  LV_LTB_1_92.MSB1_DB_PV1                                    34816 non-null  float64 x\n 22  LV_LTB_2_92.MSB2_DB_PV2                                    34821 non-null  float64 x\n 23  LV_Medical_13F.Solar_Main_Supply                           34794 non-null  float64 x\n 24  LV_N1_Building_Carpark.West_Park_Solar_Feed                31469 non-null  float64 x\n 25  LV_North_Pavilion.MSB_PV_DB                                34389 non-null  float64 x\n 26  LV_Physics_27.Solar_Main_Supply                            34774 non-null  float64 x\n 27  LV_Robert_Blackwood_Hall_2.Main_Solar_Supply               34991 non-null  float64 x\n 28  LV_Science_Theatres_East_25.Solar_Main_Supply              34738 non-null  float64 x\n 29  LV_Sport_01.PVDB-DB-A                                      33460 non-null  float64 x\n 30  LV_Sport_01.PVDB-DB-B                                      18961 non-null  float64 x\n 31  LV_Sport_01.PVDB-MSSB                                      30112 non-null  float64 x\n 32  LV_TED_B94.DB_Roof_Solar                                   13692 non-null  float64 x\n 33  LV_Turner_Hall_87.Solar_Main_Supply_unverified             34808 non-null  float64 x\n 34  Total Clayton solar connected to main HV NMI               35035 non-null  float64 n\n '

<div class="alert alert-block alert-warning">

### 2.3. Preparing Weather Dataset (Timestamp: From 31/12/2015 12:15 AM to 16/7/2021 10:45 PM) <a class="anchor" name="4_df"></a>

 </div>

In this section, the used file is **-37.912_145.134_Solcast_PT5M.csv**. The steps to prepare it are as follow:

1. Import pandas library;
2. Read -37.912_145.134_Solcast_PT5M.csv file;
3. Rename PeriodStart into ReadTime (for joining with the final PV dataset by variable name in the upcoming section);
4. Reformat the date from YYYY-MM-DD HH:MM:SS into DD/MM/YYYY HH:MM AM/PM;
5. Filter only minutes 00, 15, 30, and 45;
6. Write the final dataset into weather_data.csv file.

In [18]:
# Import Library
import pandas as pd

In [19]:
# Read CSV
weather_data = pd.read_csv("./data/-37.912_145.134_Solcast_PT5M.csv")

In [20]:
# Rename PeriodStart into ReadTime -> [We will be using PeriodStart instead of PeriodEnd]
weather_data.rename(columns = {'PeriodStart':'ReadTime'}, inplace = True)

# Re-format the ReadTime so that the final PV dataset and -37.912_145.134_Solcast_PT5M.csv files have 
# a similar date format
# Step 1. Split the date and time into 2 separate variables
weather_data[['datePV','timePV']] = weather_data["ReadTime"].str.split("T", 1, expand=True)

# Step 2. Remove Z from timePV variable
weather_data['timePV'] = weather_data['timePV'].str.replace(r'Z', '')

# Step 3. Re-format the datePV variable
# Split the datePV variable
weather_data[['yearPV','monthPV', 'dayPV']] = weather_data['datePV'].str.split('-',expand=True)
# Change dayPV format by deleting front 0 (e.g. 01, 02, etc.)
weather_data['dayPV'] = weather_data['dayPV'].apply(lambda t: str(int(t)))
# Change monthPV format by deleting front 0 (e.g. 01, 02, etc.)
weather_data['monthPV'] = weather_data['monthPV'].apply(lambda t: str(int(t)))
# Change the format from YYYY-MM-DD into DD/MM/YYYY
weather_data["datePV"] = weather_data[["dayPV", "monthPV", "yearPV"]].apply("/".join, axis=1)

# Step 4. Re-format the timePV variable
# Split the timePV variable
weather_data[['hourPV','minutePV', 'secondPV']] = weather_data['timePV'].str.split(':',expand=True)
# Create PM or AM
weather_data['AMorPM'] = weather_data['hourPV'].apply(lambda t: "AM" if int(t) / 12 < 1 else "PM")
# Change the format from HH:MM:SS into HH:MM AM/PM
weather_data['hourPV'] = weather_data['hourPV'].apply(lambda t: "12" if t == "00" else t)
weather_data['hourPV'] = weather_data['hourPV'].apply(lambda t: str(int(t) - 12) if int(t) > 12 else t)
# Change hourPV format by deleting front 0 (e.g. 01, 02, etc.)
weather_data['hourPV'] = weather_data['hourPV'].apply(lambda t: str(int(t)))
weather_data["timePV"] = weather_data[["hourPV", "minutePV"]].apply(":".join, axis=1)
weather_data["timePV"] = weather_data[["timePV", "AMorPM"]].apply(" ".join, axis=1)

# Step 4. Re-format the ReadTime
weather_data["ReadTime"] = weather_data[["datePV", "timePV"]].apply(" ".join, axis=1)

# Step 5. Filter only minutes 0, 15, 30, and 45
minutes_list = ["00", "15", "30", "45"] # Create minutes_list
weather_data2 = weather_data.loc[weather_data['minutePV'].isin(minutes_list)]

In [21]:
# Write CSV of final weather dataset
# Step 1. Exclude previously created helper variables and other unnecessary variables
weather_data2 = weather_data2.drop(['datePV', 'timePV', 'yearPV', 'monthPV', 'dayPV', 'hourPV', 'minutePV', 'secondPV', 'AMorPM', 'PeriodEnd', 'Period'], axis=1)

weather_data2

,ReadTime,AirTemp,Azimuth,CloudOpacity,Dhi,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
1,31/12/2015 12:15 AM,32.1,-70,0.0,124,946,817,942,900,1068,17.7,22.7,987.8,30,0.12
4,31/12/2015 12:30 AM,32.2,-65,0.0,125,953,845,970,935,1069,17.8,22.5,987.6,28,0.12
7,31/12/2015 12:45 AM,32.2,-60,0.0,126,958,869,996,966,1070,17.9,22.3,987.5,25,0.12
10,31/12/2015 1:00 AM,32.3,-54,0.0,127,963,890,1017,992,1071,18.0,22.0,987.4,22,0.12
13,31/12/2015 1:15 AM,32.4,-47,0.0,128,966,907,1035,1014,1071,18.1,21.8,987.3,20,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583171,16/7/2021 9:45 PM,7.6,-61,41.4,10,0,0,10,9,10,13.9,81.6,984.9,88,0.13
583174,16/7/2021 10:00 PM,7.5,-58,32.5,31,0,0,31,29,31,13.9,82.9,985.0,86,0.13
583177,16/7/2021 10:15 PM,7.5,-56,21.8,53,82,10,63,91,50,14.0,83.2,985.2,83,0.13
583180,16/7/2021 10:30 PM,7.5,-53,49.0,61,0,0,61,57,61,14.0,83.3,985.3,81,0.13
583183,16/7/2021 10:45 PM,7.5,-51,59.1,64,0,0,64,60,64,14.1,83.5,985.5,78,0.13

In [22]:
# Step 2. Generate csv files
weather_data2 = weather_data2.reset_index(drop=True) # Reset index

weather_data2.to_csv('./data/weather_data.csv', index = False)

<div class="alert alert-block alert-info">

## 3. Creating Time Series Data Analytics and Visualization App's Datasets <a class="anchor" name="TS1"></a>

</div>

<div class="alert alert-block alert-warning">

### 3.4. Distribution, Missing Value, Outlier, and Trend Pages Dataset [Timestamp after Combining: From 1/7/2020 12:15 AM to 16/7/2021 10:45 PM] <a class="anchor" name="TS2"></a>

 </div>

In this section, the used files are **weather_data.csv** (generated from section 2.3) and **PV_data.csv** (generated from section 2.2.1). The steps to combine them are as follow:

1. Import pandas library;
2. Read both weather_data.csv and PV_data.csv files;
3. Inner join to synchronize the timestamps in both datasets;
4. Reorder the final_result dataset's columns by positioning the pv data first then the weather data;
5. Write the final dataset into time_series_df.csv file.

In [23]:
# Import Library
import pandas as pd

In [24]:
# Read CSV
final_weather = pd.read_csv("./data/weather_data.csv")
final_pv = pd.read_csv("./data/PV_data.csv")

In [25]:
final_weather

,ReadTime,AirTemp,Azimuth,CloudOpacity,Dhi,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
0,31/12/2015 12:15 AM,32.1,-70,0.0,124,946,817,942,900,1068,17.7,22.7,987.8,30,0.12
1,31/12/2015 12:30 AM,32.2,-65,0.0,125,953,845,970,935,1069,17.8,22.5,987.6,28,0.12
2,31/12/2015 12:45 AM,32.2,-60,0.0,126,958,869,996,966,1070,17.9,22.3,987.5,25,0.12
3,31/12/2015 1:00 AM,32.3,-54,0.0,127,963,890,1017,992,1071,18.0,22.0,987.4,22,0.12
4,31/12/2015 1:15 AM,32.4,-47,0.0,128,966,907,1035,1014,1071,18.1,21.8,987.3,20,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194390,16/7/2021 9:45 PM,7.6,-61,41.4,10,0,0,10,9,10,13.9,81.6,984.9,88,0.13
194391,16/7/2021 10:00 PM,7.5,-58,32.5,31,0,0,31,29,31,13.9,82.9,985.0,86,0.13
194392,16/7/2021 10:15 PM,7.5,-56,21.8,53,82,10,63,91,50,14.0,83.2,985.2,83,0.13
194393,16/7/2021 10:30 PM,7.5,-53,49.0,61,0,0,61,57,61,14.0,83.3,985.3,81,0.13
194394,16/7/2021 10:45 PM,7.5,-51,59.1,64,0,0,64,60,64,14.1,83.5,985.5,78,0.13

In [26]:
final_pv

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply,Total Clayton solar connected to main HV NMI,LV_Briggs_85B.Solar_Main_Supply,LV_Jackomos_B85A.Solar_Main_Supply
0,1/7/2020 12:15 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.001,0.025,NaN,NaN
1,1/7/2020 12:30 AM,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.025,NaN,NaN
2,1/7/2020 12:45 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
3,1/7/2020 1:00 AM,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.026,NaN,NaN
4,1/7/2020 1:15 AM,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52694,31/12/2021 10:45 PM,0.007,0.000,0.006,0.001,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.0,0.000,0.003,0.033,NaN,0.002
52695,31/12/2021 11:00 PM,0.008,0.000,0.006,0.001,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.037,0.001,NaN
52696,31/12/2021 11:15 PM,0.007,0.000,0.005,0.001,0.0,0.008,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,0.0,0.001,0.004,0.043,NaN,0.000
52697,31/12/2021 11:30 PM,NaN,NaN,0.006,0.001,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.001,0.002,0.031,0.000,0.001
52698,31/12/2021 11:45 PM,0.015,0.000,0.006,0.001,0.0,NaN,0.0,NaN,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.041,NaN,NaN

In [27]:
# Combining the Final PV dataset (From 01/07/2020 to 31/12/2021) and the final weather dataset 
# (From 31/12/2015 to 16/07/2021) (i.e., the final dataset will only cover from 01/07/2020 to 16/07/2021)
final_result = final_weather.merge(final_pv)

In [28]:
final_result

,ReadTime,AirTemp,Azimuth,CloudOpacity,Dhi,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,...,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply,Total Clayton solar connected to main HV NMI,LV_Briggs_85B.Solar_Main_Supply,LV_Jackomos_B85A.Solar_Main_Supply
0,1/7/2020 12:15 AM,13.7,-31,48.9,175,1,0,175,164,176,...,0.0,0.0,0.0,0.0,0.0,0.0,0.001,0.025,NaN,NaN
1,1/7/2020 12:30 AM,14.0,-28,17.0,146,394,161,307,470,382,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.025,NaN,NaN
2,1/7/2020 12:45 AM,14.3,-24,11.4,147,472,199,347,571,429,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.024,NaN,NaN
3,1/7/2020 1:00 AM,14.5,-21,0.0,65,789,347,411,755,500,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.026,NaN,NaN
4,1/7/2020 1:15 AM,14.7,-17,0.0,65,799,363,428,779,488,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36566,16/7/2021 9:45 PM,7.6,-61,41.4,10,0,0,10,9,10,...,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.029,0.000,0.000
36567,16/7/2021 10:00 PM,7.5,-58,32.5,31,0,0,31,29,31,...,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.027,0.000,0.000
36568,16/7/2021 10:15 PM,7.5,-56,21.8,53,82,10,63,91,50,...,0.0,0.0,0.0,0.0,0.0,NaN,0.001,0.028,0.000,0.001
36569,16/7/2021 10:30 PM,7.5,-53,49.0,61,0,0,61,57,61,...,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.029,0.001,0.000
36570,16/7/2021 10:45 PM,7.5,-51,59.1,64,0,0,64,60,64,...,0.0,0.0,0.0,0.0,0.0,NaN,0.002,0.029,0.001,0.000

In [29]:
# Reorder the final_result dataset's columns by positioning the pv data first then the weather data

# Step 1. Create a list of the varible names in the pv dataset
pv_variables = list(final_pv.columns) 
# Step 1.1. Remove Total Clayton solar connected to main HV NMI variables
pv_variables.remove("Total Clayton solar connected to main HV NMI") # so that we can put it at the end
# Step 1.2. Add Total Clayton solar connected to main HV NMI variable back
pv_variables.append("Total Clayton solar connected to main HV NMI")

# Step 2. Create a list of the variable names in the weather data
weather_variables = list(final_weather.columns)
# Step 2.1. Remove ReadTime (because it will be a duplication with step 1)
weather_variables.remove("ReadTime")

# Step 3. Reorder the final_result dataset
new_ordered_variables = pv_variables + weather_variables # Combine the new reordered variables

final_result = final_result[new_ordered_variables]

In [30]:
final_result

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
0,1/7/2020 12:15 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,1,0,175,164,176,13.3,61.0,1006.9,68,0.15
1,1/7/2020 12:30 AM,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
2,1/7/2020 12:45 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,472,199,347,571,429,13.2,58.5,1006.5,65,0.15
3,1/7/2020 1:00 AM,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,789,347,411,755,500,13.2,57.3,1006.2,64,0.15
4,1/7/2020 1:15 AM,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,799,363,428,779,488,13.1,56.4,1005.9,63,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36566,16/7/2021 9:45 PM,0.008,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0,0,10,9,10,13.9,81.6,984.9,88,0.13
36567,16/7/2021 10:00 PM,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0,0,31,29,31,13.9,82.9,985.0,86,0.13
36568,16/7/2021 10:15 PM,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,82,10,63,91,50,14.0,83.2,985.2,83,0.13
36569,16/7/2021 10:30 PM,0.008,0.000,NaN,0.0,0.0,0.003,0.0,0.0,0.0,...,0,0,61,57,61,14.0,83.3,985.3,81,0.13
36570,16/7/2021 10:45 PM,0.007,0.000,NaN,0.0,0.0,0.002,0.0,0.0,0.0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13

In [31]:
# Generate csv files
final_result.to_csv('./data/time_series_df.csv', index = False)

<div class="alert alert-block alert-warning">

### 3.5. Feature Selection Page and Random Forest Modelling Dataset (i.e., For the Feature Selection Page and Random Forest Modelling) [Timestamp after Combining: From 1/7/2020 12:30 AM to 16/7/2021 10:45 PM] <a class="anchor" name="TS3"></a>

 </div>

In this section, the used files are **weather_data.csv** (generated from section 2.3) and **PV_data.csv** (generated from section 2.2.1). The steps to combine them are as follow:

1. Import pandas library;
2. Read both weather_data.csv and PV_data.csv files;
3. Convert PV_data.csv from wide to long format;
4. Create 15 minutes prior pv_values variable (i.e., pv_values_1);
5. Remove missing values;
6. Create timeTS, dayofmonth, month, year, and season variables;
7. Create building / location dummy variables;
8. Inner join to synchronize the timestamps in both datasets;
9. Write the final dataset into final_PV.csv file.

In [32]:
# Import Library
import pandas as pd

In [33]:
# Read CSV
final_weather1 = pd.read_csv("./data/weather_data.csv")
final_pv1 = pd.read_csv("./data/PV_data.csv")

In [34]:
final_weather1

,ReadTime,AirTemp,Azimuth,CloudOpacity,Dhi,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
0,31/12/2015 12:15 AM,32.1,-70,0.0,124,946,817,942,900,1068,17.7,22.7,987.8,30,0.12
1,31/12/2015 12:30 AM,32.2,-65,0.0,125,953,845,970,935,1069,17.8,22.5,987.6,28,0.12
2,31/12/2015 12:45 AM,32.2,-60,0.0,126,958,869,996,966,1070,17.9,22.3,987.5,25,0.12
3,31/12/2015 1:00 AM,32.3,-54,0.0,127,963,890,1017,992,1071,18.0,22.0,987.4,22,0.12
4,31/12/2015 1:15 AM,32.4,-47,0.0,128,966,907,1035,1014,1071,18.1,21.8,987.3,20,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194390,16/7/2021 9:45 PM,7.6,-61,41.4,10,0,0,10,9,10,13.9,81.6,984.9,88,0.13
194391,16/7/2021 10:00 PM,7.5,-58,32.5,31,0,0,31,29,31,13.9,82.9,985.0,86,0.13
194392,16/7/2021 10:15 PM,7.5,-56,21.8,53,82,10,63,91,50,14.0,83.2,985.2,83,0.13
194393,16/7/2021 10:30 PM,7.5,-53,49.0,61,0,0,61,57,61,14.0,83.3,985.3,81,0.13
194394,16/7/2021 10:45 PM,7.5,-51,59.1,64,0,0,64,60,64,14.1,83.5,985.5,78,0.13

In [35]:
final_pv1

,ReadTime,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_North_Pavilion.MSB_PV_DB,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,Campus_Centre_10.Solar_Main_Supply,LV_Law_Theatres_12.Solar_Main_Supply,LV_Medical_13F.Solar_Main_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,...,LV_Holman_Hall_88.Solar_Main_Supply-unverified,LV_Campbell_Hall_89.Solar_Main_Supply-unverified,LV_Logan_Hall_90.Solar_Main_Supply,LV_LTB_1_92.MSB1_DB_PV1,LV_LTB_2_92.MSB2_DB_PV2,LV_TED_B94.DB_Roof_Solar,LV_Chancellery_96.Solar_Main_Supply,Total Clayton solar connected to main HV NMI,LV_Briggs_85B.Solar_Main_Supply,LV_Jackomos_B85A.Solar_Main_Supply
0,1/7/2020 12:15 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.001,0.025,NaN,NaN
1,1/7/2020 12:30 AM,0.008,0.000,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.025,NaN,NaN
2,1/7/2020 12:45 AM,0.008,0.000,0.007,NaN,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
3,1/7/2020 1:00 AM,0.008,0.001,0.007,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.026,NaN,NaN
4,1/7/2020 1:15 AM,0.008,0.000,0.006,NaN,0.0,0.003,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.024,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52694,31/12/2021 10:45 PM,0.007,0.000,0.006,0.001,0.0,NaN,0.0,0.0,0.0,...,0.0,0.0,NaN,0.0,0.0,0.000,0.003,0.033,NaN,0.002
52695,31/12/2021 11:00 PM,0.008,0.000,0.006,0.001,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.037,0.001,NaN
52696,31/12/2021 11:15 PM,0.007,0.000,0.005,0.001,0.0,0.008,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,0.0,0.001,0.004,0.043,NaN,0.000
52697,31/12/2021 11:30 PM,NaN,NaN,0.006,0.001,0.0,0.002,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,NaN,0.001,0.002,0.031,0.000,0.001
52698,31/12/2021 11:45 PM,0.015,0.000,0.006,0.001,0.0,NaN,0.0,NaN,NaN,...,0.0,NaN,0.0,0.0,0.0,0.001,NaN,0.041,NaN,NaN

<div class="alert alert-block alert-warning">

#### 3.5.1. Feature Engineering <a class="anchor" name="feature_engineering"></a>

 </div>

**15 Minutes Prior Photovoltaic (PV) Value Feature**

In [36]:
# Convert final_pv1 from wide to long format
# Step 1. Change the format from wide to long
final_pv1 = pd.melt(final_pv1, id_vars='ReadTime',
                    var_name='building_names', value_name='pv_values')

# Step 2. Create 15 minutes prior pv_values variable
final_pv1['pv_values_1'] = final_pv1['pv_values'].shift(1)

# Step 3. Remove missing values
final_pv1 = final_pv1.dropna()

# Step 4. Reset index
final_pv1.reset_index(drop=True, inplace=True)

In [37]:
final_pv1

,ReadTime,building_names,pv_values,pv_values_1
0,1/7/2020 12:30 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008
1,1/7/2020 12:45 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008
2,1/7/2020 1:00 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008
3,1/7/2020 1:15 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008
4,1/7/2020 1:30 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008
...,...,...,...,...
1597215,31/12/2021 8:00 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.627,0.847
1597216,31/12/2021 8:15 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.274,0.627
1597217,31/12/2021 8:30 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.047,0.274
1597218,31/12/2021 8:45 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.000,0.047
1597219,31/12/2021 11:30 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.001,0.000

**Time, Day, Month, year, and Season Features**

In [38]:
# Step 1. Split the date and time into 2 separate variables
final_pv1[['dateTS','timeTS']] = final_pv1["ReadTime"].str.split(" ", 1, expand=True)

# Step 2. Split the dateTS variable into day, month and year (Create day, month, and year features)
final_pv1[['dayofmonth','month', 'year']] = final_pv1['dateTS'].str.split('/',expand=True)

# Convert day, month, and year into an integer datatype
final_pv1 = final_pv1.astype({"dayofmonth":"int", "month":"int", "year":"int"})

# Step 3. Create season feature
# Ref: http://www.bom.gov.au/climate/glossary/seasons.shtml
summer = [12, 1, 2] # December, January and February
autumn = [3, 4, 5] # March, April and May
winter = [6, 7, 8] # June, July and August
spring = [9, 10, 11] # September, October and November

final_pv1.loc[(final_pv1['month'].isin(summer)), 'seasonTS'] = 0
final_pv1.loc[(final_pv1['month'].isin(autumn)), 'seasonTS'] = 1
final_pv1.loc[(final_pv1['month'].isin(winter)), 'seasonTS'] = 2
final_pv1.loc[(final_pv1['month'].isin(spring)), 'seasonTS'] = 3

# Convert seasonTS into an integer datatype
final_pv1 = final_pv1.astype({"seasonTS":"int"})

# Step 4. Create time feature
# Step 4.1. Split timeTS variable into temptime and PMorAM variables by whitespace
final_pv1[['temptime','AMorPM']] = final_pv1["timeTS"].str.split(" ", 1, expand=True)

# Step 4.2. Split temptime into hourTS and minuteTS variables by semicolon
final_pv1[['hourTS','minutesTS']] = final_pv1["temptime"].str.split(":", 1, expand=True)

# Step 4.3. Convert hourTS and minuteTS into an integer datatype
final_pv1 = final_pv1.astype({"hourTS":"int", "minutesTS":"int"})

# Step 4.4. Convert AMorPM into 24hours
final_pv1.loc[(final_pv1['AMorPM'] == 'AM') & (final_pv1['hourTS'] == 12), 'hourTS'] = int(0) # 12:xx AM into 00:xx
final_pv1['hourTS'] = final_pv1.apply(lambda x: x.hourTS + int(12) if x.AMorPM == "PM" else x.hourTS, axis = 1) # xx:xx PM into 24hours

# Step 4.5. Create timeTS by calculating how many minutes have passed from 00:00 (e.g., 01:15 will be 75)
final_pv1['timeTS'] = final_pv1['hourTS'] * int(60) + final_pv1['minutesTS']

# Step 5. Drop the helper variables
final_pv1 = final_pv1.drop(['dateTS', 'temptime', 'AMorPM', 'hourTS', 'minutesTS'], axis=1)

In [39]:
final_pv1

,ReadTime,building_names,pv_values,pv_values_1,timeTS,dayofmonth,month,year,seasonTS
0,1/7/2020 12:30 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008,30,1,7,2020,2
1,1/7/2020 12:45 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008,45,1,7,2020,2
2,1/7/2020 1:00 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008,60,1,7,2020,2
3,1/7/2020 1:15 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008,75,1,7,2020,2
4,1/7/2020 1:30 AM,LV_Sport_01.PVDB-DB-A,0.008,0.008,90,1,7,2020,2
...,...,...,...,...,...,...,...,...,...
1597215,31/12/2021 8:00 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.627,0.847,1200,31,12,2021,0
1597216,31/12/2021 8:15 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.274,0.627,1215,31,12,2021,0
1597217,31/12/2021 8:30 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.047,0.274,1230,31,12,2021,0
1597218,31/12/2021 8:45 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.000,0.047,1245,31,12,2021,0
1597219,31/12/2021 11:30 PM,LV_Jackomos_B85A.Solar_Main_Supply,0.001,0.000,1410,31,12,2021,0

**Building / Location Dummy Features**

In [40]:
# Create Building / Location Dummy Features
# Adding dummy column
final_pv1 = pd.concat([final_pv1, pd.get_dummies(final_pv1['building_names'])], axis=1)

# Drop building_names and Total Clayton solar connected to main HV NMI variables
final_pv1 = final_pv1.drop(['building_names', 'Total Clayton solar connected to main HV NMI'], axis=1)

In [41]:
final_pv1

,ReadTime,pv_values,pv_values_1,timeTS,dayofmonth,month,year,seasonTS,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,...,LV_N1_Building_Carpark.West_Park_Solar_Feed,LV_North_Pavilion.MSB_PV_DB,LV_Physics_27.Solar_Main_Supply,LV_Robert_Blackwood_Hall_2.Main_Solar_Supply,LV_Science_Theatres_East_25.Solar_Main_Supply,LV_Sport_01.PVDB-DB-A,LV_Sport_01.PVDB-DB-B,LV_Sport_01.PVDB-MSSB,LV_TED_B94.DB_Roof_Solar,LV_Turner_Hall_87.Solar_Main_Supply_unverified
0,1/7/2020 12:30 AM,0.008,0.008,30,1,7,2020,2,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1/7/2020 12:45 AM,0.008,0.008,45,1,7,2020,2,0,0,...,0,0,0,0,0,1,0,0,0,0
2,1/7/2020 1:00 AM,0.008,0.008,60,1,7,2020,2,0,0,...,0,0,0,0,0,1,0,0,0,0
3,1/7/2020 1:15 AM,0.008,0.008,75,1,7,2020,2,0,0,...,0,0,0,0,0,1,0,0,0,0
4,1/7/2020 1:30 AM,0.008,0.008,90,1,7,2020,2,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1597215,31/12/2021 8:00 PM,0.627,0.847,1200,31,12,2021,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1597216,31/12/2021 8:15 PM,0.274,0.627,1215,31,12,2021,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1597217,31/12/2021 8:30 PM,0.047,0.274,1230,31,12,2021,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1597218,31/12/2021 8:45 PM,0.000,0.047,1245,31,12,2021,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1597219,31/12/2021 11:30 PM,0.001,0.000,1410,31,12,2021,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# Combine with weather data
final_result1 = final_pv1.merge(final_weather1)

# Reset index
final_result1.reset_index(drop=True, inplace=True)

In [43]:
final_result1

,ReadTime,pv_values,pv_values_1,timeTS,dayofmonth,month,year,seasonTS,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,...,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
0,1/7/2020 12:30 AM,0.008,0.008,30,1,7,2020,2,0,0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
1,1/7/2020 12:30 AM,0.000,0.000,30,1,7,2020,2,0,0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
2,1/7/2020 12:30 AM,0.007,0.007,30,1,7,2020,2,0,0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
3,1/7/2020 12:30 AM,0.000,0.000,30,1,7,2020,2,0,0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
4,1/7/2020 12:30 AM,0.003,0.002,30,1,7,2020,2,1,0,...,394,161,307,470,382,13.3,59.7,1006.7,66,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1082181,1/6/2021 12:45 PM,4.366,3.293,1485,1,6,2021,2,0,0,...,0,0,0,0,0,13.9,66.0,1012.5,155,0.15
1082182,1/6/2021 12:45 PM,8.255,6.552,1485,1,6,2021,2,0,0,...,0,0,0,0,0,13.9,66.0,1012.5,155,0.15
1082183,1/6/2021 12:45 PM,17.237,12.902,1485,1,6,2021,2,0,0,...,0,0,0,0,0,13.9,66.0,1012.5,155,0.15
1082184,1/6/2021 12:45 PM,10.454,8.086,1485,1,6,2021,2,0,0,...,0,0,0,0,0,13.9,66.0,1012.5,155,0.15
1082185,1/6/2021 12:45 PM,261.521,206.594,1485,1,6,2021,2,0,0,...,0,0,0,0,0,13.9,66.0,1012.5,155,0.15

In [44]:
# Checking the latest date of the final dataframe
final_result1[(final_result1.ReadTime == "16/7/2021 10:45 PM")]

,ReadTime,pv_values,pv_values_1,timeTS,dayofmonth,month,year,seasonTS,Campus_Centre_10.Solar_Main_Supply,LV_Accident_Research_Centre_70.Solar_Main_Supply,...,Dni,Ebh,Ghi,GtiFixedTilt,GtiTracking,PrecipitableWater,RelativeHumidity,SurfacePressure,Zenith,AlbedoDaily
1043530,16/7/2021 10:45 PM,0.007,0.008,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043531,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043532,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043533,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043534,16/7/2021 10:45 PM,0.002,0.003,1365,16,7,2021,2,1,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043535,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043536,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043537,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043538,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043539,16/7/2021 10:45 PM,0.004,0.004,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043540,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043541,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043542,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043543,16/7/2021 10:45 PM,0.012,0.011,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043544,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043545,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,1,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043546,16/7/2021 10:45 PM,0.001,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043547,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043548,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043549,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043550,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043551,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043552,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043553,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043554,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043555,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043556,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043557,16/7/2021 10:45 PM,0.002,0.002,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043558,16/7/2021 10:45 PM,0.029,0.029,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043559,16/7/2021 10:45 PM,0.001,0.001,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13
1043560,16/7/2021 10:45 PM,0.000,0.000,1365,16,7,2021,2,0,0,...,0,0,64,60,64,14.1,83.5,985.5,78,0.13

In [45]:
# Generate csv files
final_result1.to_csv('./data/selection_df.csv', index = False)

<div class="alert alert-block alert-info">
    
## 4. Summary <a class="anchor" name="summary"></a>
    
</div>

There are **five** datasets that have been generated from all of the sections above. Following are explanations of the files:

- **PV_data_first.csv:** the tidy version of the 2021_Clayton Solar PV.xlsx file which has been converted into CSV file. This file has a timestamp from 1/1/2021 12:00 AM to 31/12/2021 11:45 PM;
- **PV_data.csv:** the combination of the 2021_Clayton Solar PV.xlsx and 2020-07 to 2021-06 Clayton PV Data (verified) Pivoted.csv file. This file has a timestamp from 1/7/2020 12:15 AM to 31/12/2021 11:45 PM;
- **weather_data.csv:** the tidy version of the -37.912_145.134_Solcast_PT5M.csv file. This file has a timestamp from 31/12/2015 12:15 AM to 16/7/2021 10:45 PM;
- **time_series_df.csv:** the combination of the PV_data.csv and weather_data.csv files. This file has a timestamp from 1/7/2020 12:15 AM to 16/7/2021 10:45 PM and is used for the RShiny App (i.e., Time Series Data Analytics and Visualization App) because the dataset still contains the missing value and other anomalies;
- **selection_df.csv:** the combination of the PV_data.csv and weather_data.csv files. This file has a timestamp from 1/7/2020 12:30 AM to 16/7/2021 10:45 PM and is used for the Feature Selection Page and Random Forest Modelling because the format has been converted from wide to long and the missing values have been removed.